### ISSUE TITLE
initial PR to test workflow

### ISSUE THREAD

**Issue by uli-f** [ideaconsult/jna-inchi#2]
@ntk73 I just opened an initial PR #1 to make sure that this workflow is smooth for both of us.

Would you please take a look at the PR and then merge if you are happy with it.

Once you have done this I will continue with the next PRs.

**Comment by uli-f** [comment]
@ntk73 I continued working on the code. Once you merged this I will open another pull request that has several smaller commits.

**Comment by ntk73** [comment]
initial PR is merged
