### ISSUE TITLE
final steps

### ISSUE THREAD

**Issue by uli-f** [ideaconsult/jna-inchi#24]
I opened three small PRs that I'd like to merge before opening a PR for the rinchi branch in Dan's jna-inchi repo:

- [x] PR #21
- [x] PR #22
- [x] PR #23
- [x] PR #25

**Comment by uli-f** [comment]
Once these are merged the last thing to do is to fix the indentations and some javadoc warnings. I am happy to prepare a PR for this.

A lot of lines will be changed when carrying out these steps, but I promise not to change any actual code! 🤓

**Comment by ntk73** [comment]
@uli-f , all final PRs are merged. 
I have made one small addition to the package level documentation about the agent types (see 5db7fc45aa4168e7483a32c3caa213c4837c64b0)

**Comment by ntk73** [comment]
Concerning the final steps, I was thinking previously about updating the rna-inchi repository front page  README.md file. 
Actually, jna-rinchi is a series of sub-modules within jna-inchi, then this could be noted in the first entry point of the repo i.e. the README.md file.

**Comment by ntk73** [comment]
As well as, the release notes could be updated...

**Comment by uli-f** [comment]
> Concerning the final steps, I was thinking previously about updating the rna-inchi repository front page README.md file.
> Actually, jna-rinchi is a series of sub-modules within jna-inchi, then this could be noted in the first entry point of the repo i.e. the README.md file.

Yes, please. Good idea 😃 

> As well as, the release notes could be updated...

And again: yes, please. 🏁 

If you work these non-Java files I can do the indentations and javadoc at the same time, should be a clean merge without any conflict.
I'll work on my part tomorrow.

**Comment by ntk73** [comment]
If you have ideas for the readme and release-notes files, you could work on these as well. I plan to work on these tomorrow, so no worry about conflicts...

**Comment by uli-f** [comment]
I'll have a look at readme and release-notes 👀

**Comment by uli-f** [comment]
Two more PRs for you to merge:

- [x] PR #26 
- [x] PR #27

**Comment by uli-f** [comment]
When going over the javadocs and looking at all the files I saw a few tiny code changes I'd like to make.

As so many lines (indentation) were changed in #27 I can only start working on this once #27 is merged.

I'll also write an email to Dan and John and let them know that we are about to open a PR for the jna-inchi repo.

**Comment by uli-f** [comment]
@ntk73 Are you happy for me to add the following sentence to the release notes:

_The addition of RInChI capabilities was implemented by IdeaConsult and sponsored by Pending AI._

**Comment by vedina** [comment]
> The addition of RInChI capabilities was implemented by Ideaconsult Ltd and sponsored by Pending AI.

**Comment by ntk73** [comment]
> @ntk73 Are you happy for me to add the following sentence to the release notes:
> 
> _The addition of RInChI capabilities was implemented by IdeaConsult and sponsored by Pending AI._

As also, Nina confirmed above, this acknowledgement is OK. Just the company name needs to be corrected to  *Ideaconsult Ltd*

**Comment by ntk73** [comment]
> When going over the javadocs and looking at all the files I saw a few tiny code changes I'd like to make.
> 
> As so many lines (indentation) were changed in #27 I can only start working on this once #27 is merged.
> 

PR #26 and PR #27 are merged, so you can go ahead...
