### ISSUE TITLE
RinchiFullInfo is only used for testing

### ISSUE THREAD

**Issue by uli-f** [ideaconsult/jna-inchi#28]
The class `RinchiFullInfo` is only used for testing, more specifically in `JnaRinchiTest`.

If you agree I'd like to move the class to a static inner class within `JnaRinchiTest`.

**Comment by ntk73** [comment]
That is OK.

**Comment by uli-f** [comment]
Opened PR #29.

**Comment by ntk73** [comment]
> Opened PR #29.

PR #29 is merged
