### ISSUE TITLE
variable autoRecognizedFormat in MDLReactionReader

### ISSUE THREAD

**Issue by uli-f** [ideaconsult/jna-inchi#33]
I made some small changes in MDLReactionReader in PR #32.

I recognized an oddity that I want to bring to your attention re the variable `autoRecognizedFormat`:
- `autoRecognizedFormat` is declared on class level on line 62
- it is queried for being equal to `ReactionFileFormat.RD` on line 178:
```
if ((format == ReactionFileFormat.RD) ||
                (format == ReactionFileFormat.AUTO && autoRecognizedFormat == ReactionFileFormat.RD))
            iterateAgentsDataLines();
```
- it is not assigned to a value anywhere in the code; that means the 2nd part of the if statement will always evaluate to `false`
- my assumption is that this variable should be set in the if-else-statement in line 211-216 in `readAutoFileHeader`

Would you mind having a look and clarifying? Thanks.

**Comment by ntk73** [comment]
> 
> I recognized an oddity that I want to bring to your attention re the variable `autoRecognizedFormat`:

> Would you mind having a look and clarifying? Thanks.

You are absolutely right. I have fixed this in commit f55245d82bd262230f68f9af156e25c1760093e1 (your suggestions for code fix were exact :-) ).
