### ISSUE TITLE
ensure thread-safety for all calls to the native RInChI library in JnaRinchi

### ISSUE THREAD

**Issue by uli-f** [ideaconsult/jna-inchi#37]
- [x] introduce a `private static Object lock` in `JnaRinchi`
- [x] synchronize on this object with synchronized code blocks for all calls to the native RInChI library in `JnaRInChI`

**Comment by uli-f** [comment]
Opened PR #43

**Comment by ntk73** [comment]
PR #43 is merged and closed.
