### ISSUE TITLE
remove timeout option from RInChIOptions

### ISSUE THREAD

**Issue by uli-f** [ideaconsult/jna-inchi#40]
RinchiOptions has code for a timeoutMilliSecs option, this parameter is never used, as it cannot be passed on to the native RInChI library.

- [x] remove timeout option from `RInChIOptions`
- [x] remove timeout option from `RInChIOptions.RinchiOptionsBuilder`

**Comment by uli-f** [comment]
Opened PR #41

**Comment by ntk73** [comment]
PR #41 is merged and closed.
