### ISSUE TITLE
create parent class for RinchiOutput // RinchiInputFromRinchiOutput // RinchiKeyOutput // FileTextOutput

### ISSUE THREAD

**Issue by uli-f** [ideaconsult/jna-inchi#5]
I would like to class probably named Output or similar that is a parent class for RinchiOutput , RinchiInputFromRinchiOutput, RinchiKeyOutput, FileTextOutput and extract shared members and methods of those classes to that parent class.

Shared members/methods:
- private final int errorCode
- private final String errorMessage

If the individual status classes are getting merged into a single class (see #6) this might sit in the parent class as well.

I am happy to re-factor this if you agree.

**Comment by ntk73** [comment]
Yes, I agree. Having a common parent class is a good idea - the good practices according to OOP.

**Comment by ntk73** [comment]
I have added a new class Output and moved in it the common stuff from classes RinchiOutput, RinchiInputFromRinchiOutput, RinchiKeyOutput, FileTextOutput and RinchiDecompositionOutput (all these are made descendants of Output)
