### ISSUE TITLE
add javadocs

### ISSUE THREAD

**Issue by uli-f** [ideaconsult/jna-inchi#7]
Overall, the javadoc documentation is helpful and sufficient.

I went over all classes and had a look at the javadocs. I added/amended bits and pieces myself.

There are a few javadocs that might benefit from your knowledge of the codebase and the rinchi library:

- [x] RinchiFlag // class // just a sentence what forceEquilibrium does
- [x] ReactionFileFormat // class // in particular: what exactly happens if AUTO is chosen?
- [x] MoleculeUtils // class and all public static methods // please briefly explain what the calculations in getExplicitAtomValencies and setImplicitHydrogenAtoms are based on (e.g., 'Explicit atom valencies are inferred from the bonds and their orders connected to an atom.')
- [x] StereoUtils // class and public methods // some of the methods that are currently public might be changed to private...? If the private methods are not trivial a concise javadoc might still be beneficial as this is one of the more complex parts of the code

**Comment by uli-f** [comment]
Probably best to merge PR #3 before working on this, as I have already done quite a bit.

**Comment by ntk73** [comment]
I will see for these javadocs improvements.
And yes, after merging your latest pull request.

**Comment by ntk73** [comment]
Javadocs are ready

**Comment by uli-f** [comment]
Looks good to me 👍🏼
