### ISSUE TITLE
javadoc for FileTextUtils

### ISSUE THREAD

**Issue by uli-f** [ideaconsult/jna-inchi#9]
`FileTextUtils` might benefit from some javadoc, primarily on the class level and maybe also for some of the non trivial/longer methods on the method level.

In particular, a few options have default values (`format`, `checkParityAccordingAtomNumbering`, `guessTetrahedralChiralityFromBondsInfo`) and it might be worthwhile clearly communicating those default values in the javadocs.

This issue might be best worked on once #8 is completed.

**Comment by ntk73** [comment]
I agree that this java doc would be beneficial. I will see for this as well.

**Comment by ntk73** [comment]
I have added javadocs on class level. Option ```checkParityAccordingAtomNumbering``` is commented indirectly in the javadocs since, for now,  this flag is not made visible (I felt it this way)

**Comment by uli-f** [comment]
Thanks for putting these in, makes it much clearer to me.
